# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TdeiDialog
                                 A QGIS plugin
 TDEI
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-26
        git sha              : $Format:%H$
        copyright            : (C) 2026 by TDEI
        email                : test@test.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import QEvent, QObject, QSize, Qt
from qgis.PyQt.QtGui import QFont, QFontDatabase, QIcon, QPainter, QPixmap
from qgis.PyQt.QtWidgets import (
    QAbstractItemView,
    QApplication,
    QHeaderView,
    QLineEdit,
    QPushButton,
    QSizePolicy,
    QTableWidgetItem,
)

from .osw_qgis import (
    cache_dir_for,
    is_dataset_loaded,
    load_geojsons_into_group,
    zoom_to_dataset,
)
from .tdei_api import (
    TdeiApiError,
    authenticate,
    download_osw_zip,
    list_datasets,
    unpack_osw_package,
)

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'tdei_dialog_base.ui'))

TDEI_PRIMARY = '#32006e'
TDEI_SECONDARY = '#5f647a'
TDEI_TEXT = '#212529'


class _LoginBackgroundFilter(QObject):
    """Paint the TDEI portal login background so it covers the panel."""

    def __init__(self, pixmap, parent=None):
        super(_LoginBackgroundFilter, self).__init__(parent)
        self._pixmap = pixmap

    def eventFilter(self, obj, event):
        if event.type() == QEvent.Paint:
            painter = QPainter(obj)
            painter.setRenderHint(QPainter.SmoothPixmapTransform)
            scaled = self._pixmap.scaled(
                obj.size(),
                Qt.KeepAspectRatioByExpanding,
                Qt.SmoothTransformation)
            x = (obj.width() - scaled.width()) // 2
            y = (obj.height() - scaled.height()) // 2
            painter.drawPixmap(x, y, scaled)
            return True
        return False


class TdeiDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None, iface=None):
        """Constructor."""
        super(TdeiDialog, self).__init__(parent)
        self.setupUi(self)
        self.iface = iface
        self.access_token = None
        self._username = ''
        self._loading_dataset_id = None
        self._style_login_page()

        header = self.tblDatasets.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QHeaderView.Stretch)
        header.setSectionResizeMode(2, QHeaderView.ResizeToContents)
        self.tblDatasets.verticalHeader().setVisible(False)
        self.tblDatasets.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.btnLogin.clicked.connect(self.sign_in)
        self.btnRefresh.clicked.connect(self.load_datasets)
        self.btnLogout.clicked.connect(self.sign_out)
        self.txtUsername.returnPressed.connect(self.sign_in)
        self.txtPassword.returnPressed.connect(self.sign_in)
        self.btnShowPassword.toggled.connect(self._toggle_password)

        self.show_login()

    def _style_login_page(self):
        """Match https://portal-dev.tdei.us/login."""
        plugin_dir = os.path.dirname(__file__)
        logo_path = os.path.join(plugin_dir, 'tdei_logo.png')
        bg_path = os.path.join(plugin_dir, 'bg_login.png')
        eye_path = os.path.join(plugin_dir, 'visibility.svg')
        eye_off_path = os.path.join(plugin_dir, 'visibility_off.svg')

        self.loginHeader.setAttribute(Qt.WA_StyledBackground, True)
        self.loginCard.setAttribute(Qt.WA_StyledBackground, True)
        self.lblHeaderLogo.setAttribute(Qt.WA_StyledBackground, True)
        self.loginCard.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)

        if os.path.exists(logo_path):
            logo = QPixmap(logo_path)
            self.lblHeaderLogo.setPixmap(logo.scaled(
                44, 40, Qt.KeepAspectRatio, Qt.SmoothTransformation))
            self.lblLogo.setPixmap(logo.scaledToWidth(
                80, Qt.SmoothTransformation))

        if os.path.exists(bg_path):
            self._login_bg_filter = _LoginBackgroundFilter(
                QPixmap(bg_path), self)
            self.loginBody.installEventFilter(self._login_bg_filter)

        self.btnShowPassword.setIcon(QIcon(eye_path))
        self.btnShowPassword.setIconSize(QSize(20, 20))
        self._eye_icon = QIcon(eye_path)
        self._eye_off_icon = QIcon(eye_off_path)

        self.btnLogin.setCursor(Qt.PointingHandCursor)
        self.btnLogin.setDefault(True)
        self.btnLogin.setAutoDefault(True)
        self.lblVersion.setText('V {}'.format(self._plugin_version()))
        self._apply_open_sans()
        self.pageLogin.setStyleSheet(self._login_stylesheet())
        self._set_login_status('')

    def _plugin_version(self):
        metadata = os.path.join(os.path.dirname(__file__), 'metadata.txt')
        try:
            with open(metadata) as handle:
                for line in handle:
                    if line.startswith('version='):
                        return line.split('=', 1)[1].strip()
        except OSError:
            pass
        return '0.1'

    def _apply_open_sans(self):
        families = QFontDatabase().families()
        if 'Open Sans' not in families:
            return
        for widget in (
                self.lblTitle, self.lblSubtitle, self.lblUsername,
                self.lblPassword, self.txtUsername, self.txtPassword,
                self.btnLogin, self.lblStatus, self.lblVersion):
            font = widget.font()
            font.setFamily('Open Sans')
            widget.setFont(font)

    def _toggle_password(self, visible):
        if visible:
            self.txtPassword.setEchoMode(QLineEdit.Normal)
            self.btnShowPassword.setIcon(self._eye_off_icon)
            self.btnShowPassword.setToolTip('Hide password')
        else:
            self.txtPassword.setEchoMode(QLineEdit.Password)
            self.btnShowPassword.setIcon(self._eye_icon)
            self.btnShowPassword.setToolTip('Show password')

    def _login_stylesheet(self):
        return '''
            QWidget#loginHeader {{
                background-color: {primary};
            }}
            QLabel#lblHeaderLogo {{
                background-color: #ffffff;
                border-radius: 4px;
                padding: 2px 6px;
            }}
            QFrame#loginCard {{
                background-color: #ffffff;
                border: 1px solid rgba(0, 0, 0, 0.176);
                border-radius: 6px;
            }}
            QLabel#lblLogo {{
                margin: 15px 0px;
            }}
            QLabel#lblTitle {{
                color: {text};
                font-size: 26px;
                font-weight: 300;
                margin-bottom: 2px;
            }}
            QLabel#lblSubtitle {{
                color: {secondary};
                font-size: 14px;
                margin-bottom: 20px;
                padding-bottom: 8px;
            }}
            QLabel#lblUsername, QLabel#lblPassword {{
                color: {text};
                font-size: 16px;
                font-weight: 400;
                padding-bottom: 8px;
            }}
            QLineEdit#txtUsername, QLineEdit#txtPassword {{
                min-height: 38px;
                padding: 6px 12px;
                color: {text};
                background-color: #ffffff;
                border: 1px solid #dee2e6;
                border-radius: 6px;
                font-size: 16px;
            }}
            QLineEdit#txtPassword {{
                border-top-right-radius: 0px;
                border-bottom-right-radius: 0px;
            }}
            QLineEdit#txtUsername:focus, QLineEdit#txtPassword:focus {{
                border: 1px solid {primary};
            }}
            QToolButton#btnShowPassword {{
                background-color: #ffffff;
                border: 1px solid #ced4da;
                border-left: 1px solid #ced4da;
                border-top-left-radius: 0px;
                border-bottom-left-radius: 0px;
                border-top-right-radius: 6px;
                border-bottom-right-radius: 6px;
            }}
            QPushButton#btnLogin {{
                min-height: 38px;
                margin-top: 8px;
                padding: 6px 12px;
                color: #ffffff;
                background-color: {primary};
                border: 1px solid {primary};
                border-radius: 4px;
                font-size: 16px;
                font-weight: 600;
            }}
            QPushButton#btnLogin:hover {{
                background-color: {primary};
            }}
            QPushButton#btnLogin:disabled {{
                background-color: #cccccc;
                border-color: #cccccc;
                color: #ffffff;
            }}
            QLabel#lblStatus {{
                color: {secondary};
                font-size: 14px;
                min-height: 18px;
                padding-top: 8px;
                padding-bottom: 4px;
            }}
            QLabel#lblVersion {{
                color: {secondary};
                font-size: 12px;
                margin-top: 5px;
            }}
        '''.format(
            primary=TDEI_PRIMARY,
            secondary=TDEI_SECONDARY,
            text=TDEI_TEXT)

    def _set_login_status(self, message, error=False):
        self.lblStatus.setText(message)
        color = '#dc3545' if error else TDEI_SECONDARY
        self.lblStatus.setStyleSheet(
            'color: {0}; font-size: 14px; min-height: 18px; '
            'padding-top: 8px; padding-bottom: 4px;'.format(color))

    def show_login(self):
        self.stackedWidget.setCurrentWidget(self.pageLogin)
        self._set_login_status('')
        self.btnLogin.setEnabled(True)
        self.resize(720, 720)

    def sign_in(self):
        username = self.txtUsername.text().strip()
        password = self.txtPassword.text()
        if not username or not password:
            self._set_login_status(
                'Enter both username and password.', error=True)
            return

        self.btnLogin.setEnabled(False)
        self._set_login_status('Signing in…')
        QApplication.setOverrideCursor(Qt.WaitCursor)
        QApplication.processEvents()
        try:
            self.access_token = authenticate(username, password)
        except TdeiApiError as exc:
            self.access_token = None
            self._set_login_status(str(exc), error=True)
            self.btnLogin.setEnabled(True)
            self.txtPassword.setFocus()
            self.txtPassword.selectAll()
            return
        finally:
            QApplication.restoreOverrideCursor()

        self._username = username
        self.txtPassword.clear()
        self.lblUser.setText('Signed in as {}'.format(self._username))
        self.resize(780, 520)
        self.stackedWidget.setCurrentWidget(self.pageDatasets)
        self.load_datasets()

    def load_datasets(self):
        if not self.access_token:
            self.show_login()
            self._set_login_status('Please sign in again.', error=True)
            return

        self.lblTableStatus.setText('Loading datasets…')
        self.btnRefresh.setEnabled(False)
        QApplication.setOverrideCursor(Qt.WaitCursor)
        QApplication.processEvents()
        try:
            rows = list_datasets(self.access_token)
        except TdeiApiError as exc:
            if exc.status_code == 401:
                self.sign_out()
                self._set_login_status(
                    'Session expired. Please sign in again.', error=True)
                return
            self.lblTableStatus.setText(str(exc))
            return
        finally:
            QApplication.restoreOverrideCursor()
            self.btnRefresh.setEnabled(True)

        self._fill_table(rows)
        count = len(rows)
        if count == 1:
            self.lblTableStatus.setText('1 dataset')
        else:
            self.lblTableStatus.setText('{} datasets'.format(count))

    def view_in_qgis(self, dataset_id):
        if not dataset_id:
            self.lblTableStatus.setText('Missing tdei_dataset_id.')
            return
        if not self.access_token:
            self.show_login()
            self._set_login_status('Please sign in again.', error=True)
            return
        if is_dataset_loaded(dataset_id):
            zoom_to_dataset(dataset_id, self.iface)
            self.lblTableStatus.setText(
                'Dataset {} is already loaded.'.format(dataset_id))
            return
        if self._loading_dataset_id:
            self.lblTableStatus.setText('Another dataset is still loading.')
            return

        self._loading_dataset_id = dataset_id
        self.lblTableStatus.setText(
            'Downloading {}…'.format(dataset_id))
        QApplication.setOverrideCursor(Qt.WaitCursor)
        QApplication.processEvents()
        try:
            cache_dir = cache_dir_for(dataset_id)
            zip_path = os.path.join(cache_dir, 'package.zip')
            download_osw_zip(self.access_token, dataset_id, zip_path)
            self.lblTableStatus.setText('Extracting {}…'.format(dataset_id))
            QApplication.processEvents()
            geojsons = unpack_osw_package(
                zip_path, os.path.join(cache_dir, 'extracted'))
            self.lblTableStatus.setText(
                'Loading {} into QGIS…'.format(dataset_id))
            QApplication.processEvents()
            layers = load_geojsons_into_group(
                dataset_id, geojsons, iface=self.iface)
        except TdeiApiError as exc:
            if exc.status_code == 401:
                self.sign_out()
                self._set_login_status(
                    'Session expired. Please sign in again.', error=True)
                return
            self.lblTableStatus.setText(str(exc))
            return
        except Exception as exc:
            self.lblTableStatus.setText(
                'Could not load dataset: {}'.format(exc))
            return
        finally:
            self._loading_dataset_id = None
            QApplication.restoreOverrideCursor()

        self.lblTableStatus.setText(
            'Loaded {} layer(s) in group {}.'.format(
                len(layers), dataset_id))

    def sign_out(self):
        self.access_token = None
        self._username = ''
        self.tblDatasets.setRowCount(0)
        self.lblTableStatus.setText('')
        self.lblUser.setText('')
        self.show_login()

    def _fill_table(self, rows):
        self.tblDatasets.setRowCount(0)
        self.tblDatasets.setRowCount(len(rows))
        for row_index, (dataset_id, name) in enumerate(rows):
            id_item = QTableWidgetItem(dataset_id)
            name_item = QTableWidgetItem(name)
            self.tblDatasets.setItem(row_index, 0, id_item)
            self.tblDatasets.setItem(row_index, 1, name_item)
            view_button = QPushButton('View in QGIS')
            view_button.clicked.connect(
                lambda _checked=False, did=dataset_id: self.view_in_qgis(did))
            self.tblDatasets.setCellWidget(row_index, 2, view_button)
