# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TDEI
                                 A QGIS plugin
 TDEI
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-26
        git sha              : $Format:%H$
        copyright            : (C) 2026 by TDEI
        email                : test@test.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import QgsSettings, Qgis
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDialog, QMessageBox

# Import the code for the dialog
from .job_form import JobFormDialog
from .osw_qgis import dataset_id_from_node, prepare_osw_package_zip
from .tdei_api import TdeiApiError, submit_job
from .tdei_jobs import (
    build_request,
    form_fields,
    is_osw_package_field,
    list_jobs,
    load_job_spec,
)
from .tdei_dialog import TdeiDialog
import os.path


class TdeiPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&TDEI')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('TDEI', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'TDEI'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        view = self.iface.layerTreeView()
        if view is not None:
            view.contextMenuAboutToShow.connect(self._on_layer_context_menu)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        view = self.iface.layerTreeView()
        if view is not None:
            try:
                view.contextMenuAboutToShow.disconnect(self._on_layer_context_menu)
            except TypeError:
                pass
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&TDEI'),
                action)
            self.iface.removeToolBarIcon(action)

    def _on_layer_context_menu(self, menu):
        view = self.iface.layerTreeView()
        if view is None:
            return
        dataset_id = dataset_id_from_node(view.currentNode())
        if not dataset_id:
            return
        submenu = menu.addMenu(self.tr('TDEI Jobs'))
        for job in list_jobs():
            action = submenu.addAction(job['title'])
            action.triggered.connect(
                lambda checked=False, current=job, current_id=dataset_id:
                self._run_tdei_job(current, current_id))

    def _run_tdei_job(self, job, dataset_id):
        token = self._access_token()
        if not token:
            QMessageBox.information(
                self.iface.mainWindow(),
                'TDEI',
                'Sign in first, then run the job from the layer menu.')
            self.run()
            return
        spec = load_job_spec()
        fields = form_fields(job, spec, dataset_id=dataset_id)
        self._prefill_osw_zip(fields, dataset_id)
        dialog = JobFormDialog(job, fields, parent=self.iface.mainWindow())
        if dialog.exec_() != QDialog.Accepted:
            return
        try:
            request = build_request(
                job, fields, dialog.values(), dataset_id=dataset_id)
            result = submit_job(
                token,
                request['url'],
                json_body=request['json_body'],
                files=request['files'],
                fields=request['fields'])
        except (TdeiApiError, ValueError, OSError) as exc:
            self.iface.messageBar().pushMessage(
                'TDEI', str(exc), level=Qgis.Critical, duration=8)
            return
        job_id = (
            result.get('job_id')
            or result.get('jobId')
            or result.get('id')
            or '')
        if job_id:
            message = 'Job submitted successfully.\n\nJob ID: {}'.format(job_id)
        elif result.get('location'):
            message = 'Job submitted successfully.\n\n{}'.format(result['location'])
        else:
            message = 'Job submitted successfully.'
        QMessageBox.information(
            self.iface.mainWindow(),
            'TDEI Job',
            message)

    def _prefill_osw_zip(self, fields, dataset_id):
        if not any(is_osw_package_field(field) for field in fields):
            return
        try:
            zip_path = prepare_osw_package_zip(self.iface, dataset_id)
        except (ValueError, OSError) as exc:
            QMessageBox.warning(
                self.iface.mainWindow(),
                'TDEI Job',
                '{}\nYou can browse to a zip file instead.'.format(exc))
            return
        for field in fields:
            if is_osw_package_field(field):
                field['value'] = zip_path

    def _access_token(self):
        dialog = getattr(self, 'dlg', None)
        if dialog is None:
            return None
        return dialog.access_token

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = TdeiDialog(self.iface.mainWindow(), iface=self.iface)

        self.dlg.show()
        self.dlg.raise_()
        self.dlg.activateWindow()
